# Generated by Django 5.2.17 on 2026-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_shipment_statusevent_order_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusevent",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("payment_pending", "Payment pending"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("partially_shipped", "Partially shipped"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statusevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("payment_pending", "Payment pending"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("partially_shipped", "Partially shipped"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                max_length=20,
            ),
        ),
    ]
