# Generated by Django 5.2.17 on 2026-09-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_statusevent_from_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("refund_order", "Can refund an order"),
                    ("transition_order", "Can change an order's status"),
                ],
            },
        ),
    ]
