# Generated by Django 5.2.17 on 2026-09-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="review_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
