# Generated by Django 5.2.17 on 2026-09-28 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_review_requested_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("defective", "Defective or faulty"),
                            ("damaged", "Arrived damaged"),
                            ("wrong_item", "Wrong item sent"),
                            ("not_as_described", "Not as described"),
                            ("changed_mind", "Changed my mind"),
                            ("size_issue", "Size or fit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("photo_keys", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("received", "Received"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="return_requests", to="orders.orderitem"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
