services:
  meilisearch:
    environment:
      MEILI_ENV: production

  backend:
    env_file: .env.production
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DJANGO_DEBUG: "false"
    volumes:
      - media:/app/mediafiles

  worker:
    env_file: .env.production
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DJANGO_DEBUG: "false"
    volumes: []

  beat:
    env_file: .env.production
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DJANGO_DEBUG: "false"
    volumes: []

  frontend:
    env_file: .env.production
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start
    volumes: []

  caddy:
    env_file: .env.production
