# Generated by Django 5.2.17 on 2026-09-05 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0005_collection_sizechart_and_compliance_fields"),
        ("orders", "0003_orderitem_cart_item_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="exclude_sale_items",
            field=models.BooleanField(
                default=False,
                help_text="Skip lines already discounted against their MRP.",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="first_order_only",
            field=models.BooleanField(
                default=False, help_text="Only for a customer with no paid order yet."
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="free_shipping",
            field=models.BooleanField(
                default=False,
                help_text="Waives the shipping fee on top of any amount off (J1).",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="per_user_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Blank = unlimited per customer.", null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="scope_categories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="catalog.category"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="scope_products",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="catalog.product"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, help_text="Blank = live now.", null=True
            ),
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="cart.coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemptions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("coupon", "order"), name="uniq_coupon_per_order"
                    )
                ],
            },
        ),
    ]
