# Generated by Django 5.2.17 on 2026-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_coupon_rules_and_redemptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the abandoned-cart reminder went out (G5).",
                null=True,
            ),
        ),
    ]
