# Generated by Django 5.2.17 on 2026-09-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart_reminded_at"),
        ("catalog", "0007_product_is_custom_blank"),
        ("custom_orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="uniq_variant_per_cart",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_design",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_item",
                to="custom_orders.customdesignorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_design__isnull", True)),
                fields=("cart", "variant"),
                name="uniq_variant_per_cart",
            ),
        ),
    ]
