# Generated by Django 5.2.17 on 2026-09-02 12:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnouncementBar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=160)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Links the whole bar.",
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(/|https://)",
                                "Use a site path like /shop/ or an https:// link.",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. Leave both dates blank to run until switched off.",
                        null=True,
                    ),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
