# Generated by Django 5.2.17 on 2026-09-03 13:37

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_seed_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hero", "Hero banner"),
                            ("trust", "Trust strip"),
                            ("categories", "Shop by category"),
                            ("new_arrivals", "Just landed"),
                            ("values", "Brand values"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=60)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="home/")),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="Where the button goes.",
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(/|https://)",
                                "Use a site path like /shop/ or an https:// link.",
                            )
                        ],
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=40)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
