# Generated by Django 5.2.16 on 2026-08-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_checkout_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_item_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
