# Generated by Django 5.2.16 on 2026-08-12 20:19

import uuid
from django.db import migrations, models

# Sizes already in use get a sensible sort position; anything unrecognised sorts
# after these, alphabetically. Editable in the admin afterwards.
SIZE_ORDER = {"XXS": 1, "XS": 2, "S": 3, "M": 4, "L": 5, "XL": 6, "XXL": 7, "3XL": 8, "4XL": 9}


def backfill_options(apps, schema_editor):
    """Seed the new vocabularies from the size/color values variants already use, so
    an existing database gets an admin option list that matches its catalog."""
    Size = apps.get_model("catalog", "Size")
    Color = apps.get_model("catalog", "Color")
    variants = apps.get_model("catalog", "ProductVariant").objects.all()

    for name in {v.size.strip() for v in variants if v.size.strip()}:
        Size.objects.get_or_create(
            name=name, defaults={"display_order": SIZE_ORDER.get(name.upper(), 50)}
        )

    hexes = {}
    for variant in variants:
        name = variant.color.strip()
        if name and not hexes.get(name):
            hexes[name] = variant.color_hex.strip()
    for name, hex_ in hexes.items():
        Color.objects.get_or_create(name=name, defaults={"hex": hex_})


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('hex', models.CharField(blank=True, help_text='#RRGGBB swatch', max_length=7)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RunPython(backfill_options, migrations.RunPython.noop),
    ]
