# Generated by Django 5.2.16 on 2026-09-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_size_color_vocab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated when left blank.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
