# Generated by Django 5.2.17 on 2026-09-02 21:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_productvariant_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("hero_image", models.ImageField(blank=True, upload_to="collections/")),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Shop-by-category tile", upload_to="categories/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="care_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(default="India", max_length=60),
        ),
        migrations.AddField(
            model_name="product",
            name="fit_notes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="gsm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="GSM"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4,8}$", "An HSN code is 4 to 8 digits."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model_note",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Model is 6\'1" and wears M"',
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Printed price. Leave blank when the product is not discounted.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="GST percent. Prices are shown tax-inclusive (C3): confirm the current apparel slab with your CA before launch.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_grams",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="width_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="width_variants",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="color",
            name="hex",
            field=models.CharField(
                blank=True,
                help_text="#RRGGBB swatch",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Use a hex colour like #1f3d2b.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(
                default=False,
                help_text="Forces the New badge past its automatic window (C9).",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="color_hex",
            field=models.CharField(
                blank=True,
                help_text="#RRGGBB swatch",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Use a hex colour like #1f3d2b.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.collection"
            ),
        ),
        migrations.CreateModel(
            name="SizeChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rows",
                    models.JSONField(
                        default=list,
                        help_text='Header row first: [["Size", "Chest", "Length"], ["S", "38", "27"]]',
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("cm", "centimetres"), ("in", "inches")],
                        default="cm",
                        max_length=2,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_chart",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
