# Generated by Django 5.2.17 on 2026-09-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_collection_sizechart_and_compliance_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="hsn_code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tax_rate",
        ),
    ]
