# Generated by Django 5.2.17 on 2026-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_product_hsn_code_remove_product_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_custom_blank",
            field=models.BooleanField(default=False),
        ),
    ]
