# Generated by Django 5.2.17 on 2026-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_is_custom_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="low_stock_threshold",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Warn at or below this on-hand count. Blank uses the store default (O6).",
                null=True,
            ),
        ),
    ]
