# Generated by Django 5.2.17 on 2026-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productvariant_low_stock_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_average",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
