# Generated by Django 5.2.16 on 2026-07-12 19:57

import apps.custom_orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_file', models.FileField(upload_to=apps.custom_orders.models.design_upload_path)),
                ('mockup_file', models.FileField(blank=True, upload_to=apps.custom_orders.models.design_upload_path)),
                ('print_type_id', models.PositiveSmallIntegerField(default=1)),
                ('placement_sku', models.CharField(default='fr', help_text='e.g. fr = front', max_length=8)),
                ('width_inches', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('height_inches', models.DecimalField(decimal_places=2, default=14, max_digits=5)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('review_status', models.CharField(choices=[('auto_ok', 'Auto-approved'), ('flagged', 'Flagged for review'), ('approved', 'Manually approved'), ('rejected', 'Rejected')], default='auto_ok', max_length=10)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('submit_status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('submitted', 'Submitted to Qikink'), ('failed', 'Submission failed'), ('terminal', 'Terminal (delivered/returned/cancelled)')], default='pending_payment', max_length=16)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('qikink_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('qikink_status', models.CharField(blank=True, max_length=32)),
                ('tracking_awb', models.CharField(blank=True, max_length=64)),
                ('tracking_link', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_designs', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_designs', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
