# Generated by Django 5.2.17 on 2026-09-24 14:47

import apps.custom_orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0007_product_is_custom_blank"),
        ("orders", "0005_alter_statusevent_from_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomBlank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=160)),
                ("print_type_id", models.PositiveSmallIntegerField(default=1)),
                ("print_areas", models.JSONField(default=dict)),
                (
                    "surcharge_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{max_width_in, max_height_in, surcharge}], smallest tier first.",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_blank",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="DesignUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("r2_key_raw", models.CharField(blank=True, max_length=200)),
                ("r2_key_print", models.CharField(blank=True, max_length=200)),
                ("r2_key_mockup", models.CharField(blank=True, max_length=200)),
                ("declared_mime", models.CharField(blank=True, max_length=40)),
                ("mime", models.CharField(blank=True, max_length=40)),
                ("bytes", models.PositiveIntegerField(default=0)),
                ("width_px", models.PositiveIntegerField(default=0)),
                ("height_px", models.PositiveIntegerField(default=0)),
                ("dpi_estimate", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Awaiting upload"),
                            ("uploaded", "Uploaded, not yet sanitised"),
                            ("ready", "Sanitised and print-ready"),
                            ("failed", "Sanitisation failed"),
                        ],
                        default="uploading",
                        max_length=12,
                    ),
                ),
                ("sanitised_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("auto_ok", "Auto-approved"),
                            ("flagged", "Flagged for review"),
                            ("approved", "Manually approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("review_reason", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomDesignOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("print_type_id", models.PositiveSmallIntegerField(default=1)),
                (
                    "placement_sku",
                    models.CharField(
                        default="fr", help_text="e.g. fr = front", max_length=8
                    ),
                ),
                (
                    "width_inches",
                    models.DecimalField(decimal_places=2, default=12, max_digits=5),
                ),
                (
                    "height_inches",
                    models.DecimalField(decimal_places=2, default=14, max_digits=5),
                ),
                ("back_placement_sku", models.CharField(blank=True, max_length=8)),
                (
                    "back_width_inches",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "back_height_inches",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "print_surcharge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rights_ack_text", models.TextField(blank=True)),
                (
                    "submit_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("submitted", "Submitted to Qikink"),
                            ("failed", "Submission failed"),
                            ("terminal", "Terminal (delivered/returned/cancelled)"),
                        ],
                        default="pending_payment",
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        default=apps.custom_orders.models.generate_design_key,
                        editable=False,
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "qikink_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("qikink_status", models.CharField(blank=True, max_length=32)),
                ("qikink_last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("tracking_awb", models.CharField(blank=True, max_length=64)),
                ("tracking_link", models.URLField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                (
                    "blank_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_designs",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "back_design_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="back_orders",
                        to="custom_orders.designupload",
                    ),
                ),
                (
                    "design_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="front_orders",
                        to="custom_orders.designupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
